services:
  #database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mezhang/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mezhang/data/wordpress

networks:
  inception:
    driver: bridge
